### ISSUE TITLE
Code syntax colouring disappears in read mode

### ISSUE THREAD

**Issue by NoctisAvem** [zamsyt/obsidian-ion#1]
Hi!

Ion is my favourite theme, by far. Unfortunately, the syntax highlighting is only visible while in editing mode- as soon the reading mode is entered, it disappears.

![image](https://user-images.githubusercontent.com/74150853/229351600-86943183-f419-4f64-bd47-17637e727d3b.png)

**Comment by zamsyt** [comment]
Nice to hear you like it. Thanks for submitting the issue. I now added initial support for syntax highlighting:
![syntax highlighting example](https://user-images.githubusercontent.com/102934832/229361881-880d568c-bc72-47fb-9633-133c3af86347.png)
(You seem to have some kind of snippet, since Ion doesn't have a code background, and hasn't had any support for code highlighting till now.)

I'd love to make the theme better, but haven't been actively developing it recently. It needs quite some work to get it to a point where I'd consider it feature complete.

**Comment by zamsyt** [comment]
@NoctisAvem The change is in the beta 7 version. Let me know if it works ok for you!

**Comment by NoctisAvem** [comment]
@zamsyt: Yes, it does work now, thank you very much! 
(Maybe...in the future, if there'll be some spare time for Ion ... an inline code styling would also be great. But as it is now, it's already such a big improvement for such a cool theme.) A big thank you for your quick response, it's much appreciated!

If you'll ever need someone for additional feedback about Ion, feel free to contact me. Thanks again, and have a lovely day!

**Comment by zamsyt** [comment]
@NoctisAvem You can submit more issues for any changes you'd like to see in the theme, it can give me a better idea of what to focus on.
